//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetId { get; set; }
        public string BudgetConcept { get; set; }
        public string EstimatedCost { get; set; }
        public string FinalCost { get; set; }
        public Nullable<int> BudgetCategoryId { get; set; }
        public string Note { get; set; }
    
        public virtual Budget_Category Budget_Category { get; set; }
    }
}
