//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChicadressEntities : DbContext
    {
        public ChicadressEntities()
            : base("name=ChicadressEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Award_Category> Award_Category { get; set; }
        public virtual DbSet<Budget> Budgets { get; set; }
        public virtual DbSet<Budget_Category> Budget_Category { get; set; }
        public virtual DbSet<Catering_Policy> Catering_Policy { get; set; }
        public virtual DbSet<Event_Spaces> Event_Spaces { get; set; }
        public virtual DbSet<Guest_Details> Guest_Details { get; set; }
        public virtual DbSet<Guest_Table> Guest_Table { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Message_Status> Message_Status { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Response_Template> Response_Template { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<User_Role> User_Role { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Venue_list> Venue_list { get; set; }
        public virtual DbSet<UserActivation> UserActivations { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Tasks_Category> Tasks_Category { get; set; }
        public virtual DbSet<Business_User> Business_User { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Task> User_Task { get; set; }
        public virtual DbSet<User_FavouriteBusinessUser> User_FavouriteBusinessUser { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Task_Timing> Task_Timing { get; set; }
    }
}
