//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.User_Task = new HashSet<User_Task>();
            this.User_FavouriteBusinessUser = new HashSet<User_FavouriteBusinessUser>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string StateCity { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> MarriageDate { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> ActivationId { get; set; }
        public string PartnerName { get; set; }
        public string PartnerId { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<int> NoOfGuest { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string MyPic { get; set; }
        public string MyPartnerPic { get; set; }
    
        public virtual User_Role User_Role { get; set; }
        public virtual UserActivation UserActivation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Task> User_Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_FavouriteBusinessUser> User_FavouriteBusinessUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
