//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_FavouriteBusinessUser
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int BusinessUserId { get; set; }
        public bool Favourite { get; set; }
    
        public virtual Business_User Business_User { get; set; }
        public virtual User User { get; set; }
    }
}
