//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicadresse.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public string Message1 { get; set; }
        public Nullable<int> MessageStatusId { get; set; }
        public Nullable<int> BusinessUserId { get; set; }
    
        public virtual Message_Status Message_Status { get; set; }
        public virtual Business_User Business_User { get; set; }
    }
}
