//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicadresse.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_Template
    {
        public int TempId { get; set; }
        public string TemplateName { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public string FilesAttached { get; set; }
        public Nullable<int> BusinessUserId { get; set; }
    
        public virtual Business_User Business_User { get; set; }
    }
}
