//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chicadresse.Entities.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Activation
    {
        public int Id { get; set; }
        public System.Guid ActivationCode { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
